/** Declaration file generated by dts-gen */

export function compile(input: any): any;

export function parse(input: any, options: any): any;

export function segment(input: any, segmentLength: any): any;

export namespace hls {
    function hlsSegment(input: any, segmentLength: any, startOffset: any): any;

    function hlsSegmentPlaylist(input: any, segmentLength: any): any;

}

