/** Declaration file generated by dts-gen */

export function compile(input: any): any

export interface Parsed {
  valid: boolean
  meta?: any
  cues: [
    {
      identifier: string
      start: number
      end: number
      text: string
      styles: string
    }
  ]
}

export function parse(input: any, options: any): Parsed

export function segment(input: any, segmentLength: any): any

export namespace hls {
  function hlsSegment(input: any, segmentLength: any, startOffset: any): any

  function hlsSegmentPlaylist(input: any, segmentLength: any): any
}
